### ISSUE TITLE
Install permission error: '/usr/local/share/jupyter/nbextensions/ivvv/index.js'

### ISSUE THREAD

**Issue by crypdick** [imaging-tools/ivvv#16]
I get the following error after successfully running `pip install ivvv`. Running Anaconda Python 3 on ubuntu 4.4.0-130-generic x86_64.

```
 ~  jupyter nbextension install --py ivvv
Installing /home/ubuntu/bin/anaconda3/lib/python3.6/site-packages/ivvv/static -> ivvv
Copying: /home/ubuntu/bin/anaconda3/lib/python3.6/site-packages/ivvv/static/index.js -> /usr/local/share/jupyter/nbextensions/ivvv/index.js
Traceback (most recent call last):
  File "/home/ubuntu/bin/anaconda3/bin/jupyter-nbextension", line 11, in <module>
    sys.exit(main())
  File "/home/ubuntu/bin/anaconda3/lib/python3.6/site-packages/jupyter_core/application.py", line 266, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "/home/ubuntu/bin/anaconda3/lib/python3.6/site-packages/traitlets/config/application.py", line 658, in launch_instance
    app.start()
  File "/home/ubuntu/bin/anaconda3/lib/python3.6/site-packages/notebook/nbextensions.py", line 988, in start
    super(NBExtensionApp, self).start()
  File "/home/ubuntu/bin/anaconda3/lib/python3.6/site-packages/jupyter_core/application.py", line 255, in start
    self.subapp.start()
  File "/home/ubuntu/bin/anaconda3/lib/python3.6/site-packages/notebook/nbextensions.py", line 716, in start
    self.install_extensions()
  File "/home/ubuntu/bin/anaconda3/lib/python3.6/site-packages/notebook/nbextensions.py", line 695, in install_extensions
    **kwargs
  File "/home/ubuntu/bin/anaconda3/lib/python3.6/site-packages/notebook/nbextensions.py", line 225, in install_nbextension_python
    destination=dest, logger=logger
  File "/home/ubuntu/bin/anaconda3/lib/python3.6/site-packages/notebook/nbextensions.py", line 196, in install_nbextension
    _maybe_copy(src, dest_file, logger=logger)
  File "/home/ubuntu/bin/anaconda3/lib/python3.6/site-packages/notebook/nbextensions.py", line 1046, in _maybe_copy
    shutil.copy2(src, dest)
  File "/home/ubuntu/bin/anaconda3/lib/python3.6/shutil.py", line 257, in copy2
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/home/ubuntu/bin/anaconda3/lib/python3.6/shutil.py", line 121, in copyfile
    with open(dst, 'wb') as fdst:
PermissionError: [Errno 13] Permission denied: '/usr/local/share/jupyter/nbextensions/ivvv/index.js'
```

**Comment by toloudis** [comment]
If still at all interested, I'd like to recommend the successor to this package: `nbvv`
https://github.com/allen-cell-animated/nbvv
https://pypi.org/project/nbvv/
